[package]
name = "adxl345_driver"
version = "0.0.1"
authors = ["Michael Cummings <dragonrun1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
rppal = { path = "../rppal", features = ["hal", "hal-unproven"] }
thiserror = "1.0.20"
